# Generated by Django 6.1 on 2026-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='⌖', max_length=8, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(max_length=100, verbose_name='Специализация')),
                ('experience', models.CharField(max_length=100, verbose_name='Опыт')),
                ('quote', models.CharField(max_length=180, verbose_name='Короткая цитата')),
                ('initials', models.CharField(max_length=4, verbose_name='Инициалы')),
                ('color', models.CharField(choices=[('green', 'Зелёный'), ('blue', 'Голубой'), ('dark', 'Тёмный')], default='green', max_length=20, verbose_name='Цвет карточки')),
                ('image_url', models.URLField(blank=True, help_text='Необязательно: прямая https-ссылка на изображение', verbose_name='Ссылка на фотографию')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('route', models.CharField(max_length=120, verbose_name='Маршрут')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('confirmed', 'Подтверждена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('tag', models.CharField(max_length=40, verbose_name='Тип путешествия')),
                ('days', models.CharField(max_length=40, verbose_name='Продолжительность')),
                ('level', models.CharField(max_length=40, verbose_name='Сложность')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('season', models.CharField(max_length=80, verbose_name='Сезон')),
                ('text', models.TextField(verbose_name='Описание')),
                ('visual_style', models.CharField(choices=[('ocean', 'Океан'), ('mountain', 'Горы'), ('forest', 'Лес'), ('river', 'Река')], default='forest', max_length=20, verbose_name='Стиль иллюстрации')),
                ('image_url', models.URLField(blank=True, help_text='Необязательно: прямая https-ссылка на изображение', verbose_name='Ссылка на фотографию')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Хабаровский край · Дальний Восток', max_length=160, verbose_name='Надзаголовок')),
                ('hero_title', models.CharField(default='Там, где начинается настоящее', max_length=160, verbose_name='Главный заголовок')),
                ('hero_text', models.TextField(default='Авторские путешествия в места, где тайга встречается с океаном, а каждый день становится историей.', verbose_name='Описание')),
                ('advantages_title', models.CharField(default='Дальше — только настоящее', max_length=160, verbose_name='Заголовок преимуществ')),
                ('routes_title', models.CharField(default='Выберите своё направление', max_length=160, verbose_name='Заголовок маршрутов')),
                ('guides_title', models.CharField(default='Люди, которым доверяют путь', max_length=160, verbose_name='Заголовок команды')),
                ('request_title', models.CharField(default='Ваше приключение начинается здесь', max_length=160, verbose_name='Заголовок формы')),
                ('request_text', models.TextField(default='Оставьте контакты — наш эксперт позвонит и поможет выбрать идеальный маршрут.', verbose_name='Текст формы')),
                ('email', models.EmailField(default='hello@volniyamur.ru', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(default='+7 4212 99-00-48', max_length=40, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
            },
        ),
    ]
