# Generated by Django 6.1 on 2026-09-11 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер бронирования')),
                ('yookassa_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID платежа ЮKassa')),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ идемпотентности')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('route', models.CharField(max_length=120, verbose_name='Маршрут')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('created', 'Создан локально'), ('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён'), ('error', 'Ошибка')], default='created', max_length=20, verbose_name='Статус')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('cancellation_reason', models.CharField(blank=True, max_length=160, verbose_name='Причина отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи ЮKassa',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Специалист', 'verbose_name_plural': 'Наши специалисты'},
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_deposit',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Предоплата за бронирование'),
        ),
    ]
