# Generated by Django 6.1 on 2026-09-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_payment_alter_guide_options_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.payment', verbose_name='Платёж'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP клиента'),
        ),
    ]
