# Generated by Django 6.1 on 2026-09-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_lead_payment_payment_customer_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notification_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка отправки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notification_error',
            field=models.TextField(blank=True, verbose_name='Ошибка отправки'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление отправлено'),
        ),
    ]
