# Generated by Django 6.1 on 2026-09-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_lead_notification_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 48.480223', max_digits=9, null=True, verbose_name='Широта точки старта'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_location',
            field=models.CharField(blank=True, max_length=160, verbose_name='Точка начала маршрута'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Например: 135.071917', max_digits=9, null=True, verbose_name='Долгота точки старта'),
        ),
    ]
