# Generated by Django 6.1 on 2026-09-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_populate_renamed_route_start_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('capacity', models.PositiveSmallIntegerField(default=8, verbose_name='Всего мест')),
                ('booked_places', models.PositiveSmallIntegerField(default=0, verbose_name='Занято мест')),
                ('status', models.CharField(choices=[('open', 'Есть места'), ('few', 'Осталось мало мест'), ('waitlist', 'Лист ожидания'), ('closed', 'Набор закрыт')], default='open', max_length=12, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='Примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='content.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Календарь заездов',
                'ordering': ('start_date', 'route__order', 'route__title'),
                'constraints': [models.UniqueConstraint(fields=('route', 'start_date'), name='unique_route_departure_date')],
            },
        ),
    ]
