# Generated by Django 6.1 on 2026-09-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_routedeparture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='content.routedeparture', verbose_name='Выбранный заезд'),
        ),
    ]
