# Generated by Django 6.1 on 2026-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_lead_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='День')),
                ('path', models.CharField(max_length=255, verbose_name='Страница')),
                ('session_key', models.CharField(max_length=40, verbose_name='Анонимная сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время визита')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения сайта',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['day', 'path'], name='content_vis_day_3e1e66_idx'), models.Index(fields=['day', 'session_key'], name='content_vis_day_271aac_idx')],
            },
        ),
    ]
